FROM docker.io/rust:1.93-bookworm AS builder
WORKDIR /usr/src/haro

COPY . .

RUN cargo build -p haro --release

FROM docker.io/debian:bookworm-slim
RUN apt-get update && apt-get install -y --no-install-recommends \
        ca-certificates \
    && rm -rf /var/lib/apt/lists/*

COPY --from=builder /usr/src/haro/target/release/haro /usr/local/bin/haro

ENTRYPOINT ["/usr/local/bin/haro"]
