FROM docker.io/debian:bookworm-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
        ca-certificates \
    && rm -rf /var/lib/apt/lists/*

ARG BIN_PATH=target/release/haro
COPY ${BIN_PATH} /usr/local/bin/haro

ENTRYPOINT ["haro"]
